export const tipoCliente = [
    {"value":"prospectos","label":"prospectos"},
    {"value":"interesados","label":"interesados"},
    {"value":"compradores","label":"compradores"},
    {"value":"clientes","label":"clientes"},
    {"value":"leales","label":"leales"}

]; 
export const grupoCliente = [    
    {"value":"empresarial","label":"empresarial"},
    {"value":"personal","label":"personal"}    
]; 

export const formaPagos = [    
    {"value":"contado","label":"contado"},
    {"value":"crédito","label":"crédito"}    
];

export const formaEntregas = [    
    {"value":"Inmediato","label":"Inmediato"},
    {"value":"Mismo día","label":"Mismo día"},
    {"value":"Día siguiente","label":"Día siguiente"},
    {"value":"1 semana","label":"1 semana"}
];

export const impuestos = [    
    {"value":'0',"label":"Sin/Iva"},
    {"value":'13',"label":"IVA(13%)"}    
];

export const tipoPromociones = [    
    {"value":'agotar stock',"label":'agotar stock'},
    {"value":'descuento',"label":'descuento'},
    {"value":'nuevo producto',"label":'nuevo producto'},
    {"value":'oferta',"label":'oferta'}
];


export const tiposPersona = [    
    {"value":'Natural',"label":'Natural'},
    {"value":'Jurídica',"label":'Jurídica'}    
];
export const tiposProveedor = [    
    {"value":'Proveedor Local',"label":'Proveedor Local'},
    {"value":'Proveedor Internacional',"label":'Proveedor Internacional'}
];

export const tiposLlamada = [        
    {"value":"#f0352eb0","label":"Email"}, 
    {"value":"#99ee38b4","label":"Llamada"},                   
    {"value":"#c338eebd","label":"Reunion"}
    
];

export const pages =[
    {"value":15,"label":"15"},
    {"value":30,"label":"30"},
    {"value":50,"label":"50"}             
];


export const niveles = [
              {"value":"AR","label":"Alta Rotación (AR)"},
              {"value":"LM","label":"Lento Movimiento (LM)"},
              {"value":"OB","label":"Obsoleto (OB)"}                                 
              ];      
export const clasificaciones = [
                {"value":"A","label":"A"},
                {"value":"B","label":"B"},
                {"value":"C","label":"C"}                                 
                ];                                                         
export const tiposServicio = [
              {"value":"Bienes de Consumo","label":"Bienes de Consumo"}, 
              {"value":"Servicios","label":"Servicios"},
              {"value":"Bienes de uso Comun","label":"Bienes de uso Comun"},
              {"value":"Bienes de emergencia","label":"Bienes de emergencia"},
              {"value":"Bienes durables","label":"Bienes durables"},
              ]

export const tiposMovimiento = [           
        {"value":"Baja","label":"Baja"},
        {"value":"Traspaso","label":"Traspaso"}
]
export const subcategorias = [    
    {"label":"Aceitecomestibles","value":"Aceitecomestibles","indice":68},
    {"label":"Aderezos","value":"Aderezos","indice":68},
    {"label":"Consome","value":"Consome","indice":68},
    {"label":"Cremadecacahuate","value":"Cremadecacahuate","indice":68},
    {"label":"Cremaparacafé","value":"Cremaparacafé","indice":68},
    {"label":"Puredetomate","value":"Puredetomate","indice":68},
    {"label":"Alimentoparabebe","value":"Alimentoparabebe","indice":68},
    {"label":"Alimentoparamascotas","value":"Alimentoparamascotas","indice":68},
    {"label":"Atole","value":"Atole","indice":68},
    {"label":"Avena","value":"Avena","indice":68},
    {"label":"Azúcar","value":"Azúcar","indice":68},
    {"label":"Café","value":"Café","indice":68},
    {"label":"Cereales","value":"Cereales","indice":68},
    {"label":"Chilepiquín","value":"Chilepiquín","indice":68},
    {"label":"Especias","value":"Especias","indice":68},
    {"label":"Flanenpolvo","value":"Flanenpolvo","indice":68},
    {"label":"Formulasinfantiles","value":"Formulasinfantiles","indice":68},
    {"label":"Gelatinasenpolvo/Grenetina","value":"Gelatinasenpolvo/Grenetina","indice":68},
    {"label":"Harina","value":"Harina","indice":68},
    {"label":"Harinapreparada","value":"Harinapreparada","indice":68},
    {"label":"Mole","value":"Mole","indice":68},
    {"label":"Sal","value":"Sal","indice":68},
    {"label":"Salsasenvasadas","value":"Salsasenvasadas","indice":68},
    {"label":"Sazonadores","value":"Sazonadores","indice":68},
    {"label":"Sopasensobre","value":"Sopasensobre","indice":68},
    {"label":"Cajeta","value":"Cajeta","indice":68},
    {"label":"Catsup","value":"Catsup","indice":68},
    {"label":"Mayonesa","value":"Mayonesa","indice":68},
    {"label":"Mermelada","value":"Mermelada","indice":68},
    {"label":"Miel","value":"Miel","indice":68},
    {"label":"Te","value":"Te","indice":68},
    {"label":"Vinagre","value":"Vinagre","indice":68},
    {"label":"Huevo","value":"Huevo","indice":68},
    {"label":"Pastas.","value":"Pastas.","indice":68},
    {"label":"Aceitunas","value":"Aceitunas","indice":69},
    {"label":"Champiñonesenteros/rebanados","value":"Champiñonesenteros/rebanados","indice":69},
    {"label":"Chícharoconzanahoria","value":"Chícharoconzanahoria","indice":69},
    {"label":"Chícharosenlatados","value":"Chícharosenlatados","indice":69},
    {"label":"Frijolesenlatados","value":"Frijolesenlatados","indice":69},
    {"label":"Frutasenalmíbar","value":"Frutasenalmíbar","indice":69},
    {"label":"Sardinas","value":"Sardinas","indice":69},
    {"label":"Atúnenagua/aceite","value":"Atúnenagua/aceite","indice":69},
    {"label":"Chilesenlatados","value":"Chilesenlatados","indice":69},
    {"label":"Chilesenvasados","value":"Chilesenvasados","indice":69},
    {"label":"Ensaladasenlatadas","value":"Ensaladasenlatadas","indice":69},
    {"label":"Granosdeeloteenlatados","value":"Granosdeeloteenlatados","indice":69},
    {"label":"Sopaenlata","value":"Sopaenlata","indice":69},
    {"label":"Vegetalesenconserva.","value":"Vegetalesenconserva.","indice":69},
    {"label":"Lechecondensada","value":"Lechecondensada","indice":70},
    {"label":"Lechedeslactosada","value":"Lechedeslactosada","indice":70},
    {"label":"Lecheenpolvo","value":"Lecheenpolvo","indice":70},
    {"label":"Lecheevaporada","value":"Lecheevaporada","indice":70},
    {"label":"Lechelight","value":"Lechelight","indice":70},
    {"label":"Lechepasteurizada","value":"Lechepasteurizada","indice":70},
    {"label":"Lechesaborizada","value":"Lechesaborizada","indice":70},
    {"label":"Lechesemidescremada","value":"Lechesemidescremada","indice":70},
    {"label":"Crema","value":"Crema","indice":70},
    {"label":"Yoghurt","value":"Yoghurt","indice":70},
    {"label":"Mantequilla","value":"Mantequilla","indice":70},
    {"label":"Margarina","value":"Margarina","indice":70},
    {"label":"Mediacrema","value":"Mediacrema","indice":70},
    {"label":"Queso.","value":"Queso.","indice":70},
    {"label":"Papas","value":"Papas","indice":71},
    {"label":"Palomitas","value":"Palomitas","indice":71},
    {"label":"Friturasdemaíz","value":"Friturasdemaíz","indice":71},
    {"label":"Cacahuates","value":"Cacahuates","indice":71},
    {"label":"Botanassaladas","value":"Botanassaladas","indice":71},
    {"label":"Barrasalimenticias","value":"Barrasalimenticias","indice":71},
    {"label":"Nuecesysemillas.","value":"Nuecesysemillas.","indice":71},
    {"label":"Caramelos","value":"Caramelos","indice":72},
    {"label":"Dulcesenchilados","value":"Dulcesenchilados","indice":72},
    {"label":"Chocolatedemesa","value":"Chocolatedemesa","indice":72},
    {"label":"Chocolateenpolvo","value":"Chocolateenpolvo","indice":72},
    {"label":"Chocolates","value":"Chocolates","indice":72},
    {"label":"Gomasdemascar","value":"Gomasdemascar","indice":72},
    {"label":"Mazapán","value":"Mazapán","indice":72},
    {"label":"Malvaviscos","value":"Malvaviscos","indice":72},
    {"label":"Pulpadetamarindo","value":"Pulpadetamarindo","indice":72},
    {"label":"Pastillasdedulce","value":"Pastillasdedulce","indice":72},
    {"label":"Paletasdedulce.","value":"Paletasdedulce.","indice":72},
    {"label":"Tortillasdeharina/maíz","value":"Tortillasdeharina/maíz","indice":73},
    {"label":"Galletasdulces","value":"Galletasdulces","indice":73},
    {"label":"Galletassaladas","value":"Galletassaladas","indice":73},
    {"label":"Pastelillos","value":"Pastelillos","indice":73},
    {"label":"Pandecaja","value":"Pandecaja","indice":73},
    {"label":"Pandulce","value":"Pandulce","indice":73},
    {"label":"Panmolido","value":"Panmolido","indice":73},
    {"label":"Pantostado.","value":"Pantostado.","indice":73},
    {"label":"Aguacates","value":"Aguacates","indice":74},
    {"label":"Ajos","value":"Ajos","indice":74},
    {"label":"Cebollas","value":"Cebollas","indice":74},
    {"label":"Chiles","value":"Chiles","indice":74},
    {"label":"Cilantro/Perejil","value":"Cilantro/Perejil","indice":74},
    {"label":"Jitomate","value":"Jitomate","indice":74},
    {"label":"Papas","value":"Papas","indice":74},
    {"label":"Limones","value":"Limones","indice":74},
    {"label":"Manzanas","value":"Manzanas","indice":74},
    {"label":"Naranjas","value":"Naranjas","indice":74},
    {"label":"Plátanos.","value":"Plátanos.","indice":74},
    {"label":"Aguamineral","value":"Aguamineral","indice":75},
    {"label":"Aguanatural","value":"Aguanatural","indice":75},
    {"label":"Aguasaborizada","value":"Aguasaborizada","indice":75},
    {"label":"Jarabes","value":"Jarabes","indice":75},
    {"label":"Jugos/Néctares","value":"Jugos/Néctares","indice":75},
    {"label":"Naranjadas","value":"Naranjadas","indice":75},
    {"label":"Bebidasdesoya","value":"Bebidasdesoya","indice":75},
    {"label":"Bebidasenpolvo","value":"Bebidasenpolvo","indice":75},
    {"label":"Bebidasinfantiles","value":"Bebidasinfantiles","indice":75},
    {"label":"Bebidasisotónicas","value":"Bebidasisotónicas","indice":75},
    {"label":"Energetizantes","value":"Energetizantes","indice":75},
    {"label":"Isotónicos","value":"Isotónicos","indice":75},
    {"label":"Refrescos.","value":"Refrescos.","indice":75},
    {"label":"Bebidaspreparadas","value":"Bebidaspreparadas","indice":76},
    {"label":"Cerveza","value":"Cerveza","indice":76},
    {"label":"Anís","value":"Anís","indice":76},
    {"label":"Brandy","value":"Brandy","indice":76},
    {"label":"Ginebra","value":"Ginebra","indice":76},
    {"label":"Cordiales","value":"Cordiales","indice":76},
    {"label":"Mezcal","value":"Mezcal","indice":76},
    {"label":"Jerez","value":"Jerez","indice":76},
    {"label":"Ron","value":"Ron","indice":76},
    {"label":"Tequila","value":"Tequila","indice":76},
    {"label":"Sidra","value":"Sidra","indice":76},
    {"label":"Whiskey","value":"Whiskey","indice":76},
    {"label":"Vodka.","value":"Vodka.","indice":76},
    {"label":"Pastaslistasparacomer","value":"Pastaslistasparacomer","indice":77},
    {"label":"Sopasenvaso","value":"Sopasenvaso","indice":77},
    {"label":"CarnesyEmbutidos","value":"CarnesyEmbutidos","indice":77},
    {"label":"Salchicha","value":"Salchicha","indice":77},
    {"label":"Mortadela","value":"Mortadela","indice":77},
    {"label":"Tocino","value":"Tocino","indice":77},
    {"label":"Jamón","value":"Jamón","indice":77},
    {"label":"Manteca","value":"Manteca","indice":77},
    {"label":"Chorizo","value":"Chorizo","indice":77},
    {"label":"Carnedepuerco/res/pollo.","value":"Carnedepuerco/res/pollo.","indice":77},
    {"label":"Suero","value":"Suero","indice":78},
    {"label":"Aguaoxigenada","value":"Aguaoxigenada","indice":78},
    {"label":"Preservativos","value":"Preservativos","indice":78},
    {"label":"Alcohol","value":"Alcohol","indice":78},
    {"label":"Gasas","value":"Gasas","indice":78},
    {"label":"Analgésicos","value":"Analgésicos","indice":78},
    {"label":"Antigripales","value":"Antigripales","indice":78},
    {"label":"Antiácidos.","value":"Antiácidos.","indice":78},
    {"label":"Toallashúmedas","value":"Toallashúmedas","indice":79},
    {"label":"Aceiteparabebe","value":"Aceiteparabebe","indice":79},
    {"label":"Toallasfemeninas","value":"Toallasfemeninas","indice":79},
    {"label":"Algodón","value":"Algodón","indice":79},
    {"label":"Tinteparaelcabello","value":"Tinteparaelcabello","indice":79},
    {"label":"Biberones","value":"Biberones","indice":79},
    {"label":"Talco","value":"Talco","indice":79},
    {"label":"Cepillodedientes","value":"Cepillodedientes","indice":79},
    {"label":"Shampoo/Acondicionador","value":"Shampoo/Acondicionador","indice":79},
    {"label":"Cotonetes","value":"Cotonetes","indice":79},
    {"label":"Rastrillos","value":"Rastrillos","indice":79},
    {"label":"Cremacorporal/facial","value":"Cremacorporal/facial","indice":79},
    {"label":"Papelhigiénico","value":"Papelhigiénico","indice":79},
    {"label":"Cremaparaafeitar","value":"Cremaparaafeitar","indice":79},
    {"label":"Pañuelosfaciales","value":"Pañuelosfaciales","indice":79},
    {"label":"Dentífricos","value":"Dentífricos","indice":79},
    {"label":"Pañuelosdesechables","value":"Pañuelosdesechables","indice":79},
    {"label":"Desodorantesenbarra/aerosol","value":"Desodorantesenbarra/aerosol","indice":79},
    {"label":"Maquillaje","value":"Maquillaje","indice":79},
    {"label":"Enjuaguebucal","value":"Enjuaguebucal","indice":79},
    {"label":"Lubricantesparalabios","value":"Lubricantesparalabios","indice":79},
    {"label":"Gel/spray","value":"Gel/spray","indice":79},
    {"label":"Lociónhidratante","value":"Lociónhidratante","indice":79},
    {"label":"Jabonescorporales/tocador.","value":"Jabonescorporales/tocador.","indice":79},
    {"label":"Suavizantedetelas","value":"Suavizantedetelas","indice":80},
    {"label":"Ácidomuriático","value":"Ácidomuriático","indice":80},
    {"label":"Sosacaustica","value":"Sosacaustica","indice":80},
    {"label":"Aluminio","value":"Aluminio","indice":80},
    {"label":"Pilas","value":"Pilas","indice":80},
    {"label":"Shampoopararopa","value":"Shampoopararopa","indice":80},
    {"label":"Servilletas","value":"Servilletas","indice":80},
    {"label":"Servitoallas","value":"Servitoallas","indice":80},
    {"label":"Aromatizantes","value":"Aromatizantes","indice":80},
    {"label":"Ceraparaautomóvil","value":"Ceraparaautomóvil","indice":80},
    {"label":"Ceraparacalzados","value":"Ceraparacalzados","indice":80},
    {"label":"Pastillassanitarias","value":"Pastillassanitarias","indice":80},
    {"label":"Limpiadoreslíquidos","value":"Limpiadoreslíquidos","indice":80},
    {"label":"Limpiadoresparapisos","value":"Limpiadoresparapisos","indice":80},
    {"label":"Jabóndebarra","value":"Jabóndebarra","indice":80},
    {"label":"Cerillos","value":"Cerillos","indice":80},
    {"label":"Cloro/Blanqueador","value":"Cloro/Blanqueador","indice":80},
    {"label":"Cloropararopa","value":"Cloropararopa","indice":80},
    {"label":"Insecticidas","value":"Insecticidas","indice":80},
    {"label":"Fibraslimpiadoras","value":"Fibraslimpiadoras","indice":80},
    {"label":"Desinfectantes","value":"Desinfectantes","indice":80},
    {"label":"Detergentesparatrastes","value":"Detergentesparatrastes","indice":80},
    {"label":"Detergentepararopa.","value":"Detergentepararopa.","indice":80},
    {"label":"Paletas/Helados","value":"Paletas/Helados","indice":81},
    {"label":"Veladoras/Velas","value":"Veladoras/Velas","indice":82},
    {"label":"Cepillodeplástico","value":"Cepillodeplástico","indice":82},
    {"label":"Vasosdesechables","value":"Vasosdesechables","indice":82},
    {"label":"Cintaadhesiva","value":"Cintaadhesiva","indice":82},
    {"label":"Cucharasdeplástico","value":"Cucharasdeplástico","indice":82},
    {"label":"Escobas/Trapeadores/Mechudos","value":"Escobas/Trapeadores/Mechudos","indice":82},
    {"label":"Trampaspararatas","value":"Trampaspararatas","indice":82},
    {"label":"Tenedoresdeplástico","value":"Tenedoresdeplástico","indice":82},
    {"label":"Extensiones/Multicontacto","value":"Extensiones/Multicontacto","indice":82},
    {"label":"Recogedordemetal/plástico","value":"Recogedordemetal/plástico","indice":82},
    {"label":"Popotes","value":"Popotes","indice":82},
    {"label":"Platosdesechables","value":"Platosdesechables","indice":82},
    {"label":"Focos","value":"Focos","indice":82},
    {"label":"Fusibles","value":"Fusibles","indice":82},
    {"label":"Jergas/Franelas","value":"Jergas/Franelas","indice":82},
    {"label":"Matamoscas","value":"Matamoscas","indice":82},
    {"label":"Pegamento","value":"Pegamento","indice":82},
    {"label":"Mecate/cuerda.","value":"Mecate/cuerda.","indice":82},
    {"label":"Tarjetastelefónicas","value":"Tarjetastelefónicas","indice":83},
    {"label":"Recargasmóviles","value":"Recargasmóviles","indice":83},
    {"label":"Hielo","value":"Hielo","indice":83},
    {"label":"Cigarros.","value":"Cigarros.","indice":83}
  ]              